kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-data-pvc
  labels:
   app: minecraft
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi