apiVersion: v1
kind: PersistentVolume
metadata:
 name: minecraft-data
 labels:
  app: minecraft
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
   path: >YOUR SERVER FILEPATH HERE<
